# Generated by Django 4.1.4 on 2024-03-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_chef"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(default="success", max_length=10),
        ),
    ]
