# Generated by Django 4.1.4 on 2024-03-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_orderitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("cooking", "Cooking"),
                    ("success", "Success"),
                    ("finished", "Finished"),
                    ("out", "Out (Cancel)"),
                ],
                default="cooking",
                max_length=20,
            ),
        ),
    ]
