# Generated by Django 4.1.4 on 2024-04-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_orderitem_total_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="date_oreded", new_name="date_ordered",
        ),
    ]
