# Generated by Django 4.1.4 on 2023-05-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("age", models.IntegerField()),
                ("image", models.ImageField(upload_to="image")),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
